# Generated by Django 5.0 on 2024-01-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EC_app", "0003_alter_product_stock"),
        ("cart_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Cartiteam",
            new_name="Cartitem",
        ),
        migrations.RenameField(
            model_name="cartitem",
            old_name="quality",
            new_name="quantity",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="card_id",
        ),
        migrations.AddField(
            model_name="cart",
            name="cart_id",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
