# Generated by Django 5.0 on 2024-01-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EC_app", "0002_alter_category_options_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.CharField(max_length=20),
        ),
    ]
