# Generated by Django 5.0 on 2024-01-22 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EC_app", "0003_alter_product_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.IntegerField(),
        ),
    ]
